server:
  port: 18008

spring:
  application:
    name: collect


  datasource:
    # 主数据源 mysql
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/db_xqds_server?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
      username: root
      password: root
    # 次数据源 sqlserver
    db2:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://GZJL-SERVER\SA;DatabaseName=JD_DAQ
      username: sa
      password: ohzec-123456
    db3:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://GZJL-SERVER\SA;DatabaseName=RFMSDB
      username: sa
      password: ohzec-123456


  resources:
    static-locations: classpath:static/**

  data:
    mongodb:
      uri: mongodb://root:root_xqds@localhost/db_xqds_opc
      authentication-database: db_xqds_opc

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

xqds:
  script:
    python: C:\Python27\python.exe
    spider05: C:\server\xqds\script\19216805.py
    spider02: C:\server\xqds\script\19216802.py
    execute: true
  schedule:
    # webSocket 推送频率 0/30 * * * * ? 30秒 0 */5 * * * ? 5分钟
    websocketRate: 0 */5 * * * ?
    # 执行采集超时时间 单位 毫秒
    collectTimeOut: 120000
    # opc采集频率
    collectRate: 0/15 * * * * ?
    # 每天晚上3点定时清理
    clearRate: 0 0 3 * * ?
    # 实时推送控制策略 3秒一次
    strategyRate: 0/3 * * * * ?
    # 实时推送单个编号检定结果检定
    verificationRate: 0/10 * * * * ?
    # 两秒推送一次检定状态
    checkStateRate: 0/10 * * * * ?
    # 确定检定数据状态的时间 多久毫秒内有数据就是在鉴定
    checkStepTime: 600000
  info:
    logWsAddress: ws://192.168.0.3:18009/
    uploadPath: /upload
  condition:
    logSpider: false